--DROP TABLESPACE ezdata;
DROP TABLE IF EXISTS Ord CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Ord_contains CASCADE;
DROP TABLE IF EXISTS Package CASCADE;
DROP TABLE IF EXISTS Package_contains CASCADE;
DROP TABLE IF EXISTS Shipper CASCADE;
DROP TABLE IF EXISTS Status CASCADE;
DROP TABLE IF EXISTS Supplier CASCADE;
DROP TABLE IF EXISTS Supply_contains CASCADE;
DROP TABLE IF EXISTS Supply_ord CASCADE;
DROP TABLE IF EXISTS Warehouse_inventory CASCADE;
DROP TABLE IF EXISTS Warehouse CASCADE;
DROP TABLE IF EXISTS Payment CASCADE;
DROP TABLE IF EXISTS Ord CASCADE;



--DROP DATABASE IF EXISTS games;
--DROP USER IF EXISTS games;
